// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var BaseCache, CSDate, CSEmitter, CSError, CSEvent, CSObject, CircularList, Deque, LRUCache, List, Node, Queue, Stack, e, ref, ref1;

  e = null;


  /* istanbul ignore if */

  if (!('.coffee' in require.extensions)) {
    require('coffee-script/register');
  }

  CSObject = require('./lib/object.coffee').CSObject;

  CSError = require('./lib/error.coffee').CSError;

  CSDate = require('./lib/date.coffee').CSDate;

  Stack = require('./lib/stack.coffee').Stack;

  Deque = require('./lib/deque.coffee').Deque;

  Queue = require('./lib/queue.coffee').Queue;

  Node = require('./lib/node.coffee').Node;

  List = require('./lib/list.coffee').List;

  CircularList = require('./lib/circular_list.coffee').CircularList;

  ref = require('./lib/emitter.coffee'), CSEmitter = ref.CSEmitter, CSEvent = ref.CSEvent;

  ref1 = require('./lib/cache.coffee'), BaseCache = ref1.BaseCache, LRUCache = ref1.LRUCache;

  module.exports = e = {
    CSObject: CSObject,
    CSError: CSError,
    CSDate: CSDate,
    Stack: Stack,
    Deque: Deque,
    Queue: Queue,
    Node: Node,
    List: List,
    CircularList: CircularList,
    CSEmitter: CSEmitter,
    CSEvent: CSEvent,
    BaseCache: BaseCache,
    LRUCache: LRUCache
  };

  global.cstd = e;

}).call(this);
